server:
  port: 8000

spring:
  devtools:
    livereload.enabled: true
    restart.enabled: true
  datasource:
    url: jdbc:log4jdbc:sqlserver:/111;DatabaseName=deco;encrypt=false;
    username:
    password:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      resolve-lazily: true

logging:
  level:
    jdbc.sqlonly: OFF
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.connection: OFF
    jdbc.sqltiming: OFF
    jdbc.resultsettable: OFF

mybatis:
  type-aliases-package: com.kovi.**.dto
  mapper-locations: mapper/*.xml



